version: 2
jobs:
  build:
    docker:
      - image: didgeridoomh/mercuryos-primary:0.0.1
    steps:
      - checkout
      - run: mkdir build/
      - run: mkdir build/obj
      - run: git clone https://github.com/rm-hull/barebones-toolchain.git
      - run: cd barebones-toolchain
      - run: ./setenv.sh
      - run: make
