FROM ubuntu:latest

RUN apt-get update && apt-get install -y gcc
RUN apt-get install nasm
RUN apt-get install git
RUN apt-get install ssh
RUN apt-get install tar
RUN apt-get install gzip
RUN apt-get install ca-certificates
